# Generated by Django 4.1.5 on 2023-02-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="copy_sold",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="register",
            name="price",
            field=models.BigIntegerField(default=0),
        ),
    ]
