# Generated by Django 4.1.5 on 2023-02-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_register_copy_sold_register_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="price",
            field=models.BigIntegerField(default=100),
        ),
    ]
