# Generated by Django 4.1.5 on 2023-02-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_suggestquestion_firstname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestquestion",
            name="firstName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
