# Generated by Django 4.1.5 on 2023-02-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_alter_suggestquestion_firstname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestquestion",
            name="lastName",
            field=models.CharField(max_length=10),
        ),
    ]
